<a href="https://colab.research.google.com/github/SrilakshmiRajendran/Mathematics-statistics-for-DastaScience/blob/main/Module_3_Mathematics_and_Statistics_for_Data_Science_Assgn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Science (DS)**

**Module- 3 -Mathematics and Statistics for Data Science**

**Assignment 1**

Project Title: Mathematical & Statistical Analysis for Data Science

Assignment Task Overview
Problem Statement

A data scientist team needs to evaluate business data before applying advanced predictive
models. To support decision-making, they must use mathematical and statistical techniques to
understand patterns, relationships, and probabilities within the dataset.
In this assignment, you will build a Python-based analysis solution using Linear Algebra,
Probability, and Statistics concepts. The work must be implemented in Google Colab/ Jupyter
Notebook, or VS Code using libraries such as NumPy, Pandas, and SciPy/Statistics.
Predefined datasets and arrays are provided to ensure consistent evaluation.

**Tasks Task 1 – Linear Algebra Implementation**

Dataset: Linear Algebra Dataset:

import numpy as np

vector_a = np.array([2, 4, 6])

vector_b = np.array([1, 3, 5])

matrix_a = np.array([ [2, 1, 3], [1, 0, 2], [4, 1, 1] ])

matrix_b = np.array([ [1, 2, 0], [3, 1, 4], [2, 5, 1] ])

Activity: Using NumPy:

● Perform vector addition, subtraction, and dot product using vector_a and vector_b

● Perform matrix addition and matrix multiplication using matrix_a and matrix_b

● Calculate determinant of matrix_a

● If determinant of matrix_a is not equal to zero, then find inverse of matrix_a

● Compute eigenvalues and eigenvectors of matrix_a

In [2]:
import numpy as np
import pandas as pd
import statistics

In [28]:
#Vector Addition

vector_a = np.array([2, 4, 6])
vector_b = np.array([1, 3, 5])

vector_add=vector_a+vector_b

print("Vector Addition:",vector_add)

#Vector subtraction
vector_sub=vector_a-vector_b
print('\n'"Vector Subtraction:",vector_sub)

#Dot products of vector
vector_dot=vector_a*vector_b
print('\n'"Vector Multiplication:",vector_dot)

Vector Addition: [ 3  7 11]

Vector Subtraction: [1 1 1]

Vector Multiplication: [ 2 12 30]


In [29]:
#Matrix Addition:

matrix_a = np.array([ [2, 1, 3], [1, 0, 2], [4, 1, 1] ])
matrix_b = np.array([ [1, 2, 0], [3, 1, 4], [2, 5, 1] ])

print(matrix_a,'\n\n',matrix_b)

[[2 1 3]
 [1 0 2]
 [4 1 1]] 

 [[1 2 0]
 [3 1 4]
 [2 5 1]]


In [30]:
mat_add=matrix_a+matrix_b
print("Matrix Addition:","\n",mat_add)

mat_sub=matrix_a-matrix_b
print('\n',"Matrix Subtraction:",'\n',mat_sub)

#Matrix dot product
mat_dot=np.dot(matrix_a,matrix_b)
print('\n',"Matrix multipliaction",'\n',mat_dot)

Matrix Addition: 
 [[3 3 3]
 [4 1 6]
 [6 6 2]]

 Matrix Subtraction: 
 [[ 1 -1  3]
 [-2 -1 -2]
 [ 2 -4  0]]

 Matrix multipliaction 
 [[11 20  7]
 [ 5 12  2]
 [ 9 14  5]]


In [31]:
#Determinant of matrix_a
det_mat_a=np.linalg.det(matrix_a)
print("Determinent of matrix A is:",det_mat_a)

det_mat_b=np.linalg.det(matrix_b)
print("Determinent of matrix B is:",det_mat_b)

Determinent of matrix A is: 6.0
Determinent of matrix B is: -8.999999999999998


In [32]:
#Inverse of matrix_a
if det_mat_a!=0:
  mat_a_inverse=np.linalg.inv(matrix_a)
  print("Inverse of matrix_a is:",'\n',mat_a_inverse)

else:
  print("Matrix is singular;it has no inverse")

Inverse of matrix_a is: 
 [[-0.33333333  0.33333333  0.33333333]
 [ 1.16666667 -1.66666667 -0.16666667]
 [ 0.16666667  0.33333333 -0.16666667]]


In [33]:
#eigenvalues and eigenvectors of matrix_a
matrix_a = np.array([ [2, 1, 3],
                      [1, 0, 2],
                       [4, 1, 1] ] )
eigenvalues, eigenvectors=np.linalg.eig(matrix_a)

print("Eigen value of matrix_a is:",'\n',eigenvalues)
print("Eigen vector of matrix_b is:",'\n',eigenvectors)



Eigen value of matrix_a is: 
 [ 5.54138127 -2.         -0.54138127]
Eigen vector of matrix_b is: 
 [[-0.66037269 -0.42163702  0.17485589]
 [-0.3575134  -0.52704628 -0.96894315]
 [-0.66037269  0.73786479  0.17485589]]


Task 2 – Probability Concepts

Activity:

Using Python / NumPy / SciPy:

● Calculate probability of successful sales

● Demonstrate conditional probability using customer segments Dataset for above activity:

sales_success = [0.65, 0.35] customer_segments = ["Premium", "Regular"] segment_purchase_probability = { "Premium": 0.80, "Regular": 0.50 }


In [7]:
#Updated probability of given customer purchase
P_A = 0.40
P_B = 0.62
P_B_given_A = 0.80

P_A_given_B = (P_B_given_A * P_A) / P_B

print("Updated probability:", P_A_given_B)
print("Updated probability:", P_A_given_B * 100, "%"),


Updated probability: 0.5161290322580646
Updated probability: 51.61290322580646 %


In [1]:
#Calculate Probability of successful sales
#sales_success = [0.65, 0.35]
sales_success = [0.65, 0.35]

probability_success = sales_success[0]

print("Probability of successful sales:", probability_success)
print("Probability of successful sales:", probability_success * 100, "%")

Probability of successful sales: 0.65
Probability of successful sales: 65.0 %


In [5]:
#conditional probability using customer segments Dataset for above activity:

segment_purchase_probability = { "Premium": 0.80, "Regular": 0.50 }
customer_segments = ["Premium", "Regular"]

segment_purchase_probability = {
    "Premium": 0.80,
    "Regular": 0.50
}

premium_probability = segment_purchase_probability["Premium"]
regular_probability = segment_purchase_probability["Regular"]

print("Probability of purchase given Premium customer:",premium_probability*100,"%")

print("Probability of purchase given Regular customer:",regular_probability*100,"%")

Probability of purchase given Premium customer: 80.0 %
Probability of purchase given Regular customer: 50.0 %


● Apply Bayes’ theorem to calculate updated probability of a customer purchase

○ Formula: P(A|B) = [P(B|A) * P(A)] / P(B)

Data for Bayes’ theorem :

Data for Bayes’ theorem :
5
# Probability Dataset for Customer Purchase Analysis
# P(A): Probability that a customer is Premium
P_A = 0.40
# P(B): Probability that a customer makes a purchase
P_B = 0.62
# P(B|A): Probability that a Premium customer makes a purchase
P_B_given_A = 0.80



In [8]:
P_A = 0.40
P_B = 0.62
P_B_given_A = 0.80

P_A_given_B = (P_B_given_A * P_A) / P_B

print("Updated probability:", P_A_given_B)
print("Updated probability:", P_A_given_B * 100, "%")


Updated probability: 0.5161290322580646
Updated probability: 51.61290322580646 %


● Simulate a binomial distribution for 20 trials
Data for Binomial distribution:
# Binomial Distribution Parameters - n = number of trials, p = probability of success
n_trials = 20
success_prob = 0.65

● Generate a normal distribution and uniform distribution for the following parameters
Data for above activity:
# Distribution Parameters
normal_mean = 50
normal_std = 10
uniform_low = 0
uniform_high = 1

In [9]:
#Binominal distribution
from scipy.stats import binom

n_trials = 20
success_prob = 0.65

binomial_distribution = binom.pmf(
    range(n_trials + 1),
    n_trials,
    success_prob
)

print(binomial_distribution)

[7.60958350e-10 2.82641673e-08 4.98660666e-07 5.55650456e-06
 4.38566967e-05 2.60634083e-04 1.21008682e-03 4.49460817e-03
 1.35640854e-02 3.35872590e-02 6.86139720e-02 1.15841771e-01
 1.61351038e-01 1.84401186e-01 1.71229673e-01 1.27199186e-01
 7.38209560e-02 3.22578967e-02 9.98458708e-03 1.95187417e-03
 1.81245458e-04]


In [10]:

n_trials = 20
success_prob = 0.65

result = np.random.binomial(n_trials, success_prob)

print("Number of successful sales:", result)

Number of successful sales: 12


In [12]:
#Normal distribution

normal_mean = 50
normal_std = 10

normal_data = np.random.normal(
    normal_mean,
    normal_std,
    1000
)

print(normal_data[:10])

[47.00053145 59.42420772 44.448611   56.09055918 60.68036123 50.37164885
 37.11232916 45.22661084 54.09345246 49.37557167]


In [11]:
#Uniform distribution
uniform_low = 0
uniform_high = 1

uniform_data = np.random.uniform(
    uniform_low,
    uniform_high,
    1000
)

print(uniform_data[:10])

[0.97275476 0.23233631 0.30053217 0.52842464 0.17076061 0.03764146
 0.11644725 0.42608688 0.3692975  0.95875048]


**Task 3 – Descriptive Statistics**

Statistical Dataset

sales_data = [120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
190, 200, 210, 195, 185, 175, 165, 155, 145, 135]

Activity:

Using NumPy / Pandas / statistics library:

● Compute mean, median, and mode of sales_data

● Calculate range, variance, and standard deviation

● Measure skewness and kurtosis

● Interpret whether the dataset is symmetric, positively skewed, or negatively skewed



In [13]:

from scipy.stats import skew, kurtosis

sales_data = [120, 135, 150, 145, 160, 155, 170, 165, 180, 175,190, 200, 210, 195, 185, 175, 165, 155, 145, 135]

# Mean
mean = np.mean(sales_data)

# Median
median = np.median(sales_data)

# Mode
mode = statistics.multimode(sales_data)

# Range
data_range = np.max(sales_data) - np.min(sales_data)

# Variance
variance = np.var(sales_data)

# Standard deviation
std_dev = np.std(sales_data)

# Skewness
skewness = skew(sales_data)

# Kurtosis
kurtosis_value = kurtosis(sales_data)

print("Mean:", mean)
print("Median:", median)
print("Mode:", mode)
print("Range:", data_range)
print("Variance:", variance)
print("Standard Deviation:", std_dev)
print("Skewness:", skewness)
print("Kurtosis:", kurtosis_value)

Mean: 165.5
Median: 165.0
Mode: [135, 145, 155, 165, 175]
Range: 90
Variance: 534.75
Standard Deviation: 23.124662159694356
Skewness: 0.030143346252736614
Kurtosis: -0.7069943289224954


The mean and median of the sales data are both 165, indicating that the data is centered around 165. The dataset has multiple modes: 135, 145, 155, 165, and 175. The range is 90, showing the difference between the highest and lowest sales values. The standard deviation indicates the amount of variation in sales around the mean. The skewness is close to zero, suggesting that the dataset is approximately symmetric rather than positively or negatively skewed.

Deliverables:

Submit a project folder containing:

● Complete the assignment in Google Colab or a Jupyter Notebook.

● For Google Colab, share the notebook link with "View" access. If using Jupyter, upload the notebook to Google Drive and ensure "View" access is enabled.

● Put both the Google Colab notebook in a Google Drive folder and share that folder with view access